contao:
    backend:
        custom_js:
            - bundles/contaowrappertags/scripts/wrapper-tags.js
        custom_css:
            - bundles/contaowrappertags/scripts/wrapper-tags-flexible-c44.min.css