services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Postyou\ContaoWrapper_Tags:
    resource: ../../../src
    exclude: ../../../src/{Entity,Model,Widget,DependencyInjection,ContaoManager}