services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Postyou\ContaoWrapperTags\:
    resource: ../../../src
    exclude: ../../../src/{Entity,Model,Widget,DependencyInjection,ContaoManager,Resources,EventListener}